development:
  adapter: postgresql
  database: esc
  host: localhost
  username: bfung
  password: password
test:
  adapter: postgresql
  database: esc
  host: localhost
  username: bfung
  password: password
